require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.0.4
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'bin/**/*'
    
Layout/LineLength:
  Max: 180
  
Metrics/MethodLength:
  Max: 23

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: true
